### ISSUE TITLE
Compatibility with CiviCRM 4.6.x?

### ISSUE THREAD

**Issue by kasiawaka** [veda-consulting/uk.co.vedaconsulting.gotowebinar#18]
Hello,
Thank you for this extension. It seems to have been working on an earlier version of 4.6 but since 4.6.8, the registration is not working. There are no errors, nothing to indicate where it fails. Do you know if this extension is/will be working for 4.6.x? Can we help in any way to make it happen?
Thanks!

**Comment by veda-consulting** [comment]
Hey Kasia

I'll get Kajan to take a look and see whats wrong.

Thanks



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by krishgopi** [comment]
Hi Kasia,

New version of the extension is tested with Civi 4.6.9 and released today. Can you have a look ?

Thanks

**Comment by kasiawaka** [comment]
Fantastic, I will test it on several sites today and will report back.

**Comment by kasiawaka** [comment]
I have tested the most recent version o this extension (1.6) on a few sites using CiviCRm 4.6.x and the extension works perfectly, the CiviCRM event participants are showing up in the Citrix GoToWebinar account. Thank you!
