### ISSUE TITLE
json_decode() expects at most 3 parameters, 4 given error when on server with PHP 5.3 and below

### ISSUE THREAD

**Issue by kasiawaka** [veda-consulting/uk.co.vedaconsulting.gotowebinar#22]
This is not really the extension problem but the PHP version compatibility. On a server with an older version of PHP (5.3 and below), the json_decode expects 3 parameters in the code, not 4 (which works from PHP 5.4).

When creating/editing events, the error appears on the page and the list of existing GoToWebinar events is not populated. 

A fix is to change the file CRM/Gotowebinar/Form/Setting.php and instead of
$response = json_decode($output, TRUE, 1024, JSON_BIGINT_AS_STRING);

use
$response = json_decode(preg_replace('/("\w+"):(-?\d+(.\d+)?)/', '\1:"\2"', $output), true);

**Comment by Kajakaran** [comment]
@kasiawaka 

Thanks for your patch.

We will add this to next release

**Comment by Kajakaran** [comment]
@kasiawaka 
Added your changes to latest release v1.6.1

Thanks
