### ISSUE TITLE
Extension is passing first name, last name and email only to Citrix, if other fields are marked as required on Citrix GoToWebinar end, the sync fails silently

### ISSUE THREAD

**Issue by kasiawaka** [veda-consulting/uk.co.vedaconsulting.gotowebinar#23]
Improvement idea - also possibly for the documentation.
The extension sync with Citrix GoToWebinar only passes first name, last name and email of the registrants. This make sense in most of the cases. Possibly we could update documentation to inform users about that and indicate that thy should not mark any other fields as required in Citrix GoToWebinar interface because the sync won't work (fails silently). 
An improvement idea would be to log the failed sync in CiviCRM error log.

A side note, possibly helpful for debugging: to find out why extension sync with Citrix GoToWebinar may be failing, add the following line
CRM_Core_Error::debug_var('response', $response);

after this line:
$response = json_decode($output, TRUE);

That way, every sync action results will be recorded in the CiviCRM error log. 

Here is an example of an error log entry for a webinar that was set to require (in Citrix GoToWebinar settings) an organization name:
Apr 21 11:56:27  [info] $response = Array
(
    [errorCode] => RegistrationInvalid
    [invalidFields] => Array
        (
            [0] => organization
        )

```
[description] => Registration request is missing one or more required fields or contains fields longer than maximum input
[incident] => 6333186250559204107
```

)

while the same debug code for a properly working sync looks like this:
Apr 21 08:46:19  [info] $response = Array
(
    [registrantKey] => 8899827920320305675
    [status] => APPROVED
    [joinUrl] => https://global.gotowebinar.com/join/6722927938218166786/720568652
)

**Comment by Kajakaran** [comment]
@kasiawaka 

Added log to see any connection error as you suggested to lateset version 1.6.1

Thanks

**Comment by aruncse** [comment]
Try this its work for me
CURLOPT_HTTPHEADER     => array("Authorization: ".$accessToken, "Content-type:application/json","Accept: application/json"),

**Comment by veda-consulting** [comment]
@kasiawaka we've now included a warning which shows when you connect the civi event to the gotowebinar event. This warning shows if there are further fields required in gotowebinar beyond what CiviCRM passes therefore avoiding silent failures. Please see v2.0.0
