### ISSUE TITLE
500 Error on settings page after upgrading to 2.0.0 

### ISSUE THREAD

**Issue by curtisgrife** [veda-consulting/uk.co.vedaconsulting.gotowebinar#29]
Hello!

I was having problems with version 1.6.2 of this extension (InvalidToken    Invalid token passed) so I tried upgrading to version 2.0.0 manually by replacing the extension files. After installing the new version I get this error when visiting the settings page:

> Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gotowebinar/CRM/Gotowebinar/Form/Setting.php on line 61

Should I have uninstalled the previous version before installing this one?

Thanks for your help.

**Comment by veda-consulting** [comment]
Fixed in latest version
