### ISSUE TITLE
Installation error on MySQL 5.7

### ISSUE THREAD

**Issue by axon-obriend** [veda-consulting/uk.co.vedaconsulting.gotowebinar#32]
Environment is MySQL 5.7.21 and PHP 7.0.29

When installing the extension, CiviCRM throws a DB error trying to create the custom fields.

Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => download
    [params] => Array
        (
            [key] => uk.co.vedaconsulting.gotowebinar
            [url] => https://github.com/veda-consulting/uk.co.vedaconsulting.gotowebinar/archive/v2.0.0.zip
            [install] => 1
            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [error_code] => unknown error
            [trace] => #0 [internal function]: CRM_Core_Error::exceptionHandler(Object(DB_Error))
#1 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func(Array, Object(DB_Error))
#2 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct('DB Error: unkno...', -1, 16, Array, 'INSERT INTO civ...')
#3 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-1, 16, Array, 'INSERT INTO civ...')
#4 [internal function]: PEAR->_raiseError(Object(DB_mysqli), NULL, -1, NULL, NULL, 'INSERT INTO civ...', 'DB_Error', true)
#5 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array(Array, Array)
#6 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->__call('raiseError', Array)
#7 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -1, NULL, NULL, 'INSERT INTO civ...', 'DB_Error', true)
#8 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-1, NULL, NULL, NULL, '1292 ** Incorre...')
#9 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#10 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysqli->simpleQuery('INSERT INTO civ...')
#11 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(2446): DB_common->query('INSERT INTO civ...')
#12 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(1068): DB_DataObject->_query('INSERT INTO civ...')
#13 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Core/DAO.php(502): DB_DataObject->insert()
#14 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(132): CRM_Core_DAO->save()
#15 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(213): CRM_Utils_Migrate_Import->copyData(Object(CRM_Core_DAO_CustomGroup), Object(SimpleXMLElement), true, 'name')
#16 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(80): CRM_Utils_Migrate_Import->customGroups(Object(SimpleXMLElement), Array)
#17 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(58): CRM_Utils_Migrate_Import->runXmlElement(Object(SimpleXMLElement))
#18 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gotowebinar/gotowebinar.php(39): CRM_Utils_Migrate_Import->run('/var/www/sandbo...')
#19 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(76): gotowebinar_civicrm_install()
#20 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(48): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), 'install')
#21 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/CRM/Extension/Manager.php(234): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info))
#22 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/api/v3/Extension.php(258): CRM_Extension_Manager->install(Array)
#23 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_download(Array)
#24 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#25 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest(Array)
#26 /var/www/sandbox.sustainabilityprofessionals.org/htdocs/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->runSafe('Extension', 'download', Array, NULL)
#27 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(113): civicrm_api('Extension', 'download', Array)
#28 phar:///usr/local/bin/cv/src/Command/ExtensionDownloadCommand.php(146): Civi\Cv\Command\BaseCommand->callApiSuccess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 'Extension', 'download', Array)
#29 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(257): Civi\Cv\Command\ExtensionDownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(850): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Civi\Cv\Command\ExtensionDownloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 phar:///usr/local/bin/cv/src/Application.php(17): Symfony\Component\Console\Application->run()
#34 phar:///usr/local/bin/cv/bin/cv(22): Civi\Cv\Application::main('phar:///usr/loc...')
#35 /usr/local/bin/cv(10): require('phar:///usr/loc...')
#36 {main}
            [is_error] => 1
            [error_message] => DB Error: unknown error
        )

)

The problem is the "Created Date" properties in auto_install.xml. See also [VOL-299](https://github.com/civicrm/org.civicrm.volunteer/pull/464).

**Comment by veda-consulting** [comment]
Fixed in latest version
