### ISSUE TITLE
Password field is a regular text field instead of a password field

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting/uk.co.vedaconsulting.gotowebinar#34]
CRM/GoToWebinar/Form/Setting.php - line 87

Should perhaps change this from a field of type 'text' to field of type 'password'.

Thanks.

**Comment by veda-consulting** [comment]
This change has been incorporated in the latest versions

**Comment by freeform-sg** [comment]
@veda-consulting Thanks! :)
