### ISSUE TITLE
OAuth authentication

### ISSUE THREAD

**Issue by lcdservices** [veda-consulting/uk.co.vedaconsulting.gotowebinar#35]
We just received notification that OAuth authentication will stop working on Oct 1, 2019, in favor of OAuth v2. It looks like this extension is using the older endpoint.

> NOTICE: We are disabling legacy OAuth authentication APIs in the near future. If you and your clients are already using strict OAuth 2.0 (https://api.getgo.com/oauth/v2) for GoTo API authentication, this announcement has no impact on the use of our service. If you are using the legacy authentication endpoint (https://api.getgo.com/oauth), please continue reading. Legacy OAuth authentication APIs will stop working October 1st, 2019.
> We informed you at the beginning of last year about LogMeIn GoTo Developer Center and API enforcement of the strict OAuth 2.0 authentication protocol to improve security of our API program. This change requires your action.
> We are extending support of old API endpoints that use older OAuth to acknowledge the ask for more time to migrate customers to the updated versions of the integrations. However, you must migrate your code by October 1st to use the new authentication API available at https://api.getgo.com/oauth/v2.

**Comment by herbdool** [comment]
Getting closer to that deadline. Is there a plan to keep supporting this extension or should we notify clients that they should no longer use this? Thank you. @veda-consulting

**Comment by LMKWeb** [comment]
We are contracting with a developer to update the API, since the deadline is around the corner. I will share the changes once complete, but it will most likely be after Oct 1 has passed.

**Comment by herbdool** [comment]
@LMKWeb that's good news. I've also been working on this for a client who really needs it. Perhaps we could join efforts?

**Comment by LMKWeb** [comment]
@herbdool Possibly! I'm not working on this personally, however, and our dev may not have availability to start until next week or the week after.

**Comment by herbdool** [comment]
@LMKWeb @lcdservices  I've worked on it and I think it's ready for testing: https://github.com/freeform/uk.co.vedaconsulting.gotowebinar. Download the git repo or the zip file of the master branch (https://github.com/freeform/uk.co.vedaconsulting.gotowebinar/archive/master.zip).

I've added an upgrade script though it can't account for all info. With the new Oauth version we also need to store a refresh_token so we can renew the access_token regularly (once an hour). If your access_token is still valid when upgrading (I haven't tested) it'll be fine for up to an hour than you'll find that you'll need to create an "app" with GoToWebinar to get a Consumer Key and Consumer Secret. Those we store in CiviCRM. You also need the login credentials for GoToWebinar but they're not saved in CiviCRM. So you'll need to manually enter in all this info the first time.

Once it's connected it'll hopefully be running relatively smoothly. Sometimes you might go to the settings page and see that it says the access_token is invalid. Refreshing the page should do the trick: it'll attempt the refresh_token in the background. It'll also do that in the background when managing events with webinars so it'll hopefully be smooth experience.

I haven't fully tested it so I hope you can do that to find any bugs. I'm going to get a client to test it too.

Ultimately need to figure out if Veda Consulting will continue to maintain this and incorporate the fork or if I should publish this separately. We'll see.

**Comment by veda-consulting** [comment]
@lcdservices @herbdool as mentioned we've also updated our version.
