### ISSUE TITLE
GTW update - registrants no longer sync

### ISSUE THREAD

**Issue by LMKWeb** [veda-consulting/uk.co.vedaconsulting.gotowebinar#36]
GoToWebinar appears to have made a platform update - the UI is completely new. On the heels of this, registrations from CiviCRM are no longer being passed to GTW. From within CiviCRM, it still appears as though our account is connected and it's correctly pulling the upcoming webinars and webinar keys. This information is also being carried into the CiviEvent itself. However, there is no registrant data in GTW. Is there a log or something we can check to find out where the failure is happening?

**Comment by herbdool** [comment]
I suspect it needs to update to using v2 of the REST API https://goto-developer.logmeininc.com/content/gotowebinar-api-reference-v2

**Comment by herbdool** [comment]
@LMKWeb are you interested in testing this fork https://github.com/freeform/uk.co.vedaconsulting.gotowebinar? It's working well for a client now. It uses the new API (mostly).

**Comment by LMKWeb** [comment]
@herbdool We implemented this a little over a week ago and so far it's working well on our end too! No issues to report. Thanks for your work on this!

**Comment by herbdool** [comment]
@LMKWeb great! Make sure you have the latest version. I made a tweak to fix an issue a client was having with some of the registrants not going through to GTW. I improved the access token refreshing.

**Comment by LMKWeb** [comment]
Thanks Herb - I'll check it out!

**Comment by veda-consulting** [comment]
@LMKWeb @herbdool we've now updated our version with the latest V2 APIs
@herbdool sorry we didn't take your changes, it was a bit of an exercise for a junior member of staff and they missed your fork.
