### ISSUE TITLE
Will you accept changes from a fork?

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.gotowebinar#37]
We are using this fork https://github.com/freeform/uk.co.vedaconsulting.gotowebinar in production for a couple clients and it is working well. It upgrades to Oauth2 as required by GTW.

At this point your original extension is probably not working for anyone since it uses the obsolete Oauth. I propose working together to get your extension up to date. And if not, an alternative would be to switch the official extension on civicrm.org to use our fork instead. It would be good to get your thoughts on the matter. Thank you.

@veda-consulting @deepak-srivastava @Kajakaran @vajeevan @krishgopi

**Comment by veda-consulting** [comment]
@herbdool sorry about doubling up the work but we've used it as a bit of a training exercise internally.
